-- migration_036_syllabus_remap_suggestions_origin.sql
--
-- Syllabus-driven topic mapping — orphaned-resource extension.
--
-- WHY: generateSyllabusRemapSuggestions.js has always generated suggestions
-- for exactly one population — content pointing at a subject's OLD,
-- superseded topics/subtopics (topic_id/subtopic_id non-null but not part
-- of the current confirmed tree). This migration supports a second,
-- confirmed-real population: resources with topic_id IS NULL AND
-- subtopic_id IS NULL — never tagged at all, not "outdated," just never
-- assigned. Confirmed via direct production query: 55 resources total in
-- this state, ~34 of them in subjects that already have a confirmed
-- syllabus and an active topic tree to assign into (2 subjects — both
-- Chemistry rows with zero confirmed syllabus documents at all — are out
-- of scope for this script entirely; there's no tree to assign into until
-- a syllabus is uploaded and confirmed for them, which is a prerequisite
-- this script cannot and should not try to route around).
--
-- The review UI (SyllabusRemapPage.jsx / SyllabusUnmatchedPage.jsx) needs
-- to tell these two populations apart — "this was outdated" reads very
-- differently to an admin than "this was never categorized in the first
-- place" — hence this column, rather than trying to infer origin later
-- from source_old_topic_id/source_old_subtopic_id being null (which would
-- work today but is an implicit, fragile signal to build a UI label on
-- top of; an explicit column is what it actually means).
--
-- DEFAULT 'old_tree' on the new column means every existing row (all
-- generated by the old-tree path so far, confirmed — this script has never
-- had any other suggestion source before now) is correctly labeled
-- without needing a backfill decision or a data migration beyond the
-- column addition itself.
--
-- SAFETY MODEL: purely additive. ADD COLUMN IF NOT EXISTS with a DEFAULT
-- backfills existing rows automatically in one metadata+data operation;
-- safe to re-run.
--
-- Manual run required, same as migration_007 onward — not in setupDb.js's
-- auto-run list.

BEGIN;

ALTER TABLE syllabus_remap_suggestions
  ADD COLUMN IF NOT EXISTS origin VARCHAR(20) NOT NULL DEFAULT 'old_tree';

DO $$ BEGIN
  ALTER TABLE syllabus_remap_suggestions
    ADD CONSTRAINT syllabus_remap_suggestions_origin_check
    CHECK (origin IN ('old_tree', 'orphaned'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Sanity check before committing — expect every existing row to already
-- read 'old_tree' (the default), and the constraint to exist.
SELECT
  origin, COUNT(*)
FROM syllabus_remap_suggestions
GROUP BY origin;

-- COMMIT;
-- ROLLBACK;
